repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml

- repo: https://github.com/jackdewinter/pymarkdown
  rev: "main"
  hooks:
  - id: pymarkdown

- repo: https://github.com/floatingpurr/sync_with_poetry
  rev: "1.1.0" # the revision or tag to clone at
  hooks:
    - id: sync_with_poetry
