site_name: DER Control Modules Site
theme:
  features:
    - navigation.instant
    - navigation.instant.prefetch
  name: material

plugins:
  - caption

nav:
  - Home: index.md
  - Interoperability Framework: interoperability-framework.md
#  - Controls: controls/index.md
  - Agents:
    - Interoperability Agent: interoperability.md
    - Real-Time Control Agent: rt-control.md
  - OpenFMB: openfmb.md
